// <auto-generated />
using System;
using HighSchoolDB.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HighSchoolDB.Migrations
{
    [DbContext(typeof(SampleDbContext))]
    partial class SampleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HighSchoolDB.Models.TblBetyg", b =>
                {
                    b.Property<string>("BBokstav")
                        .HasColumnName("B_Bokstav")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("BVärde")
                        .HasColumnName("B_Värde")
                        .HasColumnType("float");

                    b.HasKey("BBokstav");

                    b.ToTable("tblBetyg");
                });

            modelBuilder.Entity("HighSchoolDB.Models.TblElever", b =>
                {
                    b.Property<double>("EId")
                        .HasColumnName("E_ID")
                        .HasColumnType("float");

                    b.Property<string>("EEfternamn")
                        .HasColumnName("E_Efternamn")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("EFörnamn")
                        .HasColumnName("E_Förnamn")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("EKlassId")
                        .HasColumnName("E_Klass_ID")
                        .HasColumnType("float");

                    b.Property<string>("EPersonnummer")
                        .HasColumnName("E_Personnummer")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("EId");

                    b.HasIndex("EKlassId");

                    b.ToTable("tblElever");
                });

            modelBuilder.Entity("HighSchoolDB.Models.TblEleverKurser", b =>
                {
                    b.Property<double>("EkId")
                        .HasColumnName("EK_ID")
                        .HasColumnType("float");

                    b.Property<string>("EkBetyg")
                        .HasColumnName("EK_Betyg")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("EkBetygDatum")
                        .HasColumnName("EK_BetygDatum")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double>("EkElevId")
                        .HasColumnName("EK_ElevID")
                        .HasColumnType("float");

                    b.Property<double>("EkKursId")
                        .HasColumnName("EK_KursID")
                        .HasColumnType("float");

                    b.HasKey("EkId");

                    b.HasIndex("EkBetyg");

                    b.HasIndex("EkElevId");

                    b.HasIndex("EkKursId");

                    b.ToTable("tblEleverKurser");
                });

            modelBuilder.Entity("HighSchoolDB.Models.TblKlasser", b =>
                {
                    b.Property<double>("KlId")
                        .HasColumnName("Kl_ID")
                        .HasColumnType("float");

                    b.Property<string>("KlKlassNamn")
                        .HasColumnName("Kl_KlassNamn")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("KlId");

                    b.ToTable("tblKlasser");
                });

            modelBuilder.Entity("HighSchoolDB.Models.TblKurser", b =>
                {
                    b.Property<double>("KId")
                        .HasColumnName("K_ID")
                        .HasColumnType("float");

                    b.Property<string>("KNamn")
                        .IsRequired()
                        .HasColumnName("K_Namn")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int?>("KPoäng")
                        .HasColumnName("K_Poäng")
                        .HasColumnType("int");

                    b.HasKey("KId");

                    b.ToTable("tblKurser");
                });

            modelBuilder.Entity("HighSchoolDB.Models.TblKurserPersonal", b =>
                {
                    b.Property<double>("KpId")
                        .HasColumnName("KP_ID")
                        .HasColumnType("float");

                    b.Property<double?>("KpKursId")
                        .HasColumnName("KP_KursID")
                        .HasColumnType("float");

                    b.Property<double?>("KpPersonalId")
                        .HasColumnName("KP_PersonalID")
                        .HasColumnType("float");

                    b.HasKey("KpId");

                    b.HasIndex("KpKursId");

                    b.HasIndex("KpPersonalId");

                    b.ToTable("tblKurserPersonal");
                });

            modelBuilder.Entity("HighSchoolDB.Models.TblLärare", b =>
                {
                    b.Property<double>("LId")
                        .HasColumnName("L_ID")
                        .HasColumnType("float");

                    b.Property<double?>("LKlassId")
                        .HasColumnName("L_KlassID")
                        .HasColumnType("float");

                    b.HasKey("LId");

                    b.HasIndex("LKlassId");

                    b.ToTable("tblLärare");
                });

            modelBuilder.Entity("HighSchoolDB.Models.TblPersonal", b =>
                {
                    b.Property<double>("PId")
                        .HasColumnName("P_ID")
                        .HasColumnType("float");

                    b.Property<string>("PArbete")
                        .HasColumnName("P_Arbete")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("PEfternamn")
                        .HasColumnName("P_Efternamn")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("PFörnamn")
                        .HasColumnName("P_Förnamn")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("PId");

                    b.ToTable("tblPersonal_");
                });

            modelBuilder.Entity("HighSchoolDB.Models.TblElever", b =>
                {
                    b.HasOne("HighSchoolDB.Models.TblKlasser", "EKlass")
                        .WithMany("TblElever")
                        .HasForeignKey("EKlassId")
                        .HasConstraintName("FK_tblElever_tblKlasser");
                });

            modelBuilder.Entity("HighSchoolDB.Models.TblEleverKurser", b =>
                {
                    b.HasOne("HighSchoolDB.Models.TblBetyg", "EkBetygNavigation")
                        .WithMany("TblEleverKurser")
                        .HasForeignKey("EkBetyg")
                        .HasConstraintName("FK_EK_Betyg");

                    b.HasOne("HighSchoolDB.Models.TblElever", "EkElev")
                        .WithMany("TblEleverKurser")
                        .HasForeignKey("EkElevId")
                        .HasConstraintName("FK_tblEleverKurser_tblElever")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HighSchoolDB.Models.TblKurser", "EkKurs")
                        .WithMany("TblEleverKurser")
                        .HasForeignKey("EkKursId")
                        .HasConstraintName("FK_tblEleverKurser_tblKurser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HighSchoolDB.Models.TblKurserPersonal", b =>
                {
                    b.HasOne("HighSchoolDB.Models.TblKurser", "KpKurs")
                        .WithMany("TblKurserPersonal")
                        .HasForeignKey("KpKursId")
                        .HasConstraintName("FK_tblKurserPersonal_tblKurser");

                    b.HasOne("HighSchoolDB.Models.TblLärare", "KpPersonal")
                        .WithMany("TblKurserPersonal")
                        .HasForeignKey("KpPersonalId")
                        .HasConstraintName("FK_tblKurserPersonal_tblLärare");
                });

            modelBuilder.Entity("HighSchoolDB.Models.TblLärare", b =>
                {
                    b.HasOne("HighSchoolDB.Models.TblPersonal", "L")
                        .WithOne("TblLärare")
                        .HasForeignKey("HighSchoolDB.Models.TblLärare", "LId")
                        .HasConstraintName("FK_tblLärare_tblPersonal_")
                        .IsRequired();

                    b.HasOne("HighSchoolDB.Models.TblKlasser", "LKlass")
                        .WithMany("TblLärare")
                        .HasForeignKey("LKlassId")
                        .HasConstraintName("FK_tblLärare_tblKlasser");
                });
#pragma warning restore 612, 618
        }
    }
}
